{% extends 'layout/layout.html' %}
{% block content %}
    <div class="row">
        <div class="col-md-offset-2 col-lg-8 col-md-12">
            <div class="card">
                <div class="card-header" data-background-color="purple">
                    <h3 class="title">Coordonnées</h3>
                    <p class="category">Retrouvez les informations de l'entreprise</p>
                </div>
                <form id="online" method="POST" action="/coordonnees">
                    <div class="card-content">
                        <div><img src="../assets/img/logo.png" alt="logo Onlineformapro"></div>
                        <div id="nomOnline" contenteditable="true">Onlineformapro Vesoul</div>
                        <div id="adresseOnline" contenteditable="true">19 rue du Praley, 70000 Vesoul</div>
                        <div id="telephoneOnline" contenteditable="true">03.84.76.52.44</div>
                    </div>
                    <div class="card-footer">
                        <button id="maj" class="btn btn-primary">Mettre à jour</button>
                        <button id="default" class="btn btn-primary">Valeur par défaut</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}
