{% extends 'layout/layout.html' %}
{% block content %}
<div class="col-md-offset-3 col-lg-6 col-md-12">
    <div class="card">
        <div class="card-header" data-background-color="purple">
            <h3 class="title">Liste des stagiaires de la formation en cours</h3>
        </div>
        <div class="card-content table-responsive">
            <table class="table table-hover">
                <thead class="text-warning" style="color:purple;">
                <th>Nom</th>
                <th>Prenom</th>
                <th>Email</th>
                <th>Télephone</th>
                <th>CP</th>
                <th>Ville</th>
                </thead>
                <tbody>
                <tr>
                    <td></td>
                    <td>Cédric</td>
                    <td></td>
                    <td>06.06.06.06.06</td>
                    <td>70000</td>
                    <td></td>
                </tr>
                <tr>
                    <td></td>
                    <td>Romain</td>
                    <td></td>
                    <td>06.06.06.06.06</td>
                    <td>70170</td>
                    <td></td>
                </tr>
                <tr>
                    <td></td>
                    <td>Sarah</td>
                    <td></td>
                    <td>06.06.06.06.06</td>
                    <td>70300</td>
                    <td></td>
                </tr>
                <tr>
                    <td></td>
                    <td>Clément</td>
                    <td></td>
                    <td>06.06.06.06.06</td>
                    <td>70100</td>
                    <td></td>
                </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}
