{% extends 'layout/layout.html' %}
{% block content %}
<div class="col-md-offset-3 col-lg-6 col-md-12">
    <div class="card">
        <div class="card-header" data-background-color="purple">
            <h4 class="title">Liste des stagiaires</h4>
            <p class="category">Retrouvez la liste des stagiaires de la promo actuelle</p>
        </div>
        <div class="card-content table-responsive">
            <table class="table table-hover">
                <thead class="text-warning" style="color:purple;">
                    <th>Nom</th>
                    <th>Prenom</th>
                    <th>Email</th>
                    <th>Télephone</th>
                    <th>CP</th>
                    <th>Ville</th>
                </thead>
                <tbody id="stage">
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}
