{% extends 'layout/layout.html' %}
{% block content %}
<div class="row">
    <div class="col-md-offset-2 col-lg-8 col-md-12">
        <div class="card">
            <div class="card-header" data-background-color="purple">
                <h4 class="title">Créer une formation</h4>
                <p class="category">Créer une nouvelle formation via ce formulaire.</p>
            </div>
            <div class="col-md-offset-2 col-md-3">
                <div class="form-group label-floating">
                    <label>Date de début</label>
                    <input type="text" id="dateDebut" class="form-control" >
                </div>
            </div>
            <div class="col-md-offset-2 col-md-3">
                <div class="form-group label-floating">
                    <label>Date de fin</label>
                    <input type="text" id="dateFin" class="form-control" >
                </div>
            </div>
            <div class="col-md-offset-2 col-md-3">
                <div class="form-group label-floating">
                    <label>Places de la Région</label>
                    <input type="number" id="placeRegion" class="form-control" >
                </div>
            </div>
            <div class="col-md-offset-2 col-md-3">
                <div class="form-group label-floating">
                    <label>Places supplémentaires</label>
                    <input type="number" id="placeSupp" class="form-control" >
                </div>
            </div>
            <div class="col-md-offset-2 col-md-3">
                <div class="form-group label-floating">
                    <label>Intitulé de la formation</label>
                    <input type="text" id="intitule" class="form-control" >
                </div>
            </div>
            <div class="col-md-offset-2 col-md-3">
                <div class="form-group label-floating">
                    <label>Nom du titre</label>
                    <input type="text" id="titre" class="form-control" >
                </div>
            </div>
            <div class="col-md-offset-3 col-md-6">
                <div class="form-group label-floating">
                    <label>Logos des financeurs</label>
                    <div class="col-md-12"><img src="../assets/img/logobfc.png " style="height: 85px;width: 70px;margin-bottom: 5px;" alt="logo Conseil regional"></div>
                </div>
            </div>
            <div class="col-md-offset-3 col-md-6">
                <div class="form-group label-floating">
                    <button id="maj" class="btn btn-primary">Mettre à jour</button>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}
