{% extends 'layout/layout.html' %}
{% block content %}
<div class="col-md-12">
  <div id="map" style="height: 300px; width: 100%;">
      <p>Veuillez patienter pendant le chargement de la carte...</p>
  </div>
</div>
<div class="col-md-6">
    <div class="card">
        <div class="card-header" data-background-color="purple">
            <h3 class="title">Jours de visite</h3>
        </div>
        <div class="card-content table-responsive">
        	<table class="table table-hover">
                <thead class="text-warning text-center" style="color:orange;">
                	<th class="text-center" >Jours </th>
                	<th class="text-center" >Nombre de rdv</th>
                    <th class="text-center" >Adresse - Ville</th>
                    <th></th>
                   
                </thead>
                <tbody id="jvisite">
            	</tbody>
            </table>
        </div>
	</div>
</div>
<div class="col-md-6">
    <div class="card">
        <div class="card-header" data-background-color="purple">
            <h3 class="title">Feuille de route</h3>
        </div>
        <div class="card-content table-responsive">
            <div id="panel">Veuillez au moins cliquer un bouton "Charger la map" pour afficher les indications.</div>
        </div>
    </div>
    <div id="panel"></div>
</div>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDMNHNUUq__EVRbC45mTLCsD1H7d0M4P08 &callback=myMap&language=fr"></script>
<script src="assets/js/functions.js"></script>
{% endblock %}
