{% extends 'layout/layout.html' %}
{% block content %}
<div class="col-md-offset-3 col-lg-6 col-md-12">
  <div id="map" style="height: 300px">
            <p>Veuillez patienter pendant le chargement de la carte...</p>
    </div>
    <div class="card">
        <div class="card-header" data-background-color="purple">
            <h3 class="title">Jours de visite</h3>
        </div>
        <div class="card-content table-responsive">
        	<table class="table table-hover">
                <thead class="text-warning text-center" style="color:orange;">
                	<th class="text-center" >Jours </th>
                	<th class="text-center" >Nombre de rdv</th>
                    <th class="text-center" >Adresse - Ville</th>
                    <th></th>
                   
                </thead>
                <tbody id="jvisite">
            	</tbody>
            </table>
        </div>
        <div id="panel"></div>      
	</div>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDMNHNUUq__EVRbC45mTLCsD1H7d0M4P08 &callback=myMap&language=fr"></script>
    <script src="assets/js/functions.js"></script>
</div>
{% endblock %}
