{% extends 'layout/layout.html' %}
{% block content %}
<div class="col-md-offset-3 col-lg-6 col-md-12">
    <div class="card">
        <div class="card-header" data-background-color="purple">
            <h3 class="title">Jours de visite</h3>
        </div>
        <div class="card-content table-responsive">
        	<table class="table table-hover">
                <thead class="text-warning" style="color:orange;">
                	<th>Jours</th>
                	<th>Nombre de rendez-vous</th>
                </thead>
                <tbody>
                	<tr>
                    	<td><div id="nom" name="nom" contenteditable="true">Date</div></td>
                    	<td><div id="nom" name="nom" contenteditable="true"></div></td>
                	</tr>
            	</tbody>
            </table>
        </div>
	</div>
</div>
{% endblock %}